import * as fs from 'fs';
import * as path from 'path';
import { KnowledgeStorage } from './storage';
import { GraphEngine } from './graph';

export class KnowledgeReporter {
  private workspaceRoot: string;
  private storage: KnowledgeStorage;
  private graph: GraphEngine;

  constructor(workspaceRoot: string, storage: KnowledgeStorage, graph: GraphEngine) {
    this.workspaceRoot = workspaceRoot;
    this.storage = storage;
    this.graph = graph;
  }

  /**
   * Generates live Markdown Knowledge Base (KNOWLEDGE_BASE.md)
   */
  public async generateMarkdownReport(outputPath?: string): Promise<string> {
    const targetFile = outputPath || path.join(this.workspaceRoot, 'KNOWLEDGE_BASE.md');
    const stats = this.graph.getStats();

    // Group files by top-level directory
    const moduleMap = new Map<string, string[]>();
    for (const filePath of this.storage.files.keys()) {
      const topDir = filePath.includes('/') ? filePath.split('/')[0] : 'root';
      if (!moduleMap.has(topDir)) {
        moduleMap.set(topDir, []);
      }
      moduleMap.get(topDir)!.push(filePath);
    }

    // Find routes
    const routes = Array.from(this.storage.nodes.values()).filter((n) => n.kind === 'route');

    let md = `# OmniKB Live Knowledge Base & Code Architecture Map\n\n`;
    md += `> **Auto-Updated**: ${new Date(stats.lastSyncTime).toISOString()} | **Indexed Files**: ${stats.totalFiles} | **Total Symbols**: ${stats.totalNodes} | **Call & Dependency Edges**: ${stats.totalEdges}\n\n`;

    md += `## 1. Executive Architecture Overview\n\n`;
    md += `| Metric | Count |\n`;
    md += `| :--- | :--- |\n`;
    md += `| **Source Files** | \`${stats.totalFiles}\` |\n`;
    md += `| **Functions & Methods** | \`${(stats.nodesByKind.function || 0) + (stats.nodesByKind.method || 0)}\` |\n`;
    md += `| **Classes & Interfaces** | \`${(stats.nodesByKind.class || 0) + (stats.nodesByKind.interface || 0)}\` |\n`;
    md += `| **Web Routes / API Endpoints** | \`${routes.length}\` |\n`;
    md += `| **Languages** | ${Object.entries(stats.languages).map(([l, c]) => `\`${l}: ${c}\``).join(', ')} |\n\n`;

    md += `## 2. High Centrality Components (God Nodes & Hotspots)\n\n`;
    md += `The most referenced and interconnected symbols in this repository:\n\n`;
    md += `| Symbol | File Path | Total Connections | Inbound Callers | Outbound Calls |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- |\n`;

    for (const node of stats.godNodes.slice(0, 8)) {
      md += `| **\`${node.name}\`** | \`${node.filePath}\` | **${node.degree}** | ${node.inDegree} | ${node.outDegree} |\n`;
    }
    md += `\n`;

    if (routes.length > 0) {
      md += `## 3. Web & API Route Registry\n\n`;
      md += `| HTTP Method & Route | File Definition |\n`;
      md += `| :--- | :--- |\n`;
      for (const r of routes) {
        md += `| \`${r.name}\` | \`${r.filePath}:${r.startLine}\` |\n`;
      }
      md += `\n`;
    }

    md += `## 4. Module Map & Component Directory\n\n`;
    for (const [moduleName, files] of moduleMap.entries()) {
      md += `### \`/${moduleName}\` (${files.length} files)\n`;
      for (const f of files.slice(0, 10)) {
        const fileNodeCount = this.storage.fileNodesIndex.get(f)?.size || 0;
        md += `- **\`${f}\`**: \`${fileNodeCount} symbols\`\n`;
      }
      if (files.length > 10) {
        md += `- *(and ${files.length - 10} more files)*\n`;
      }
      md += `\n`;
    }

    md += `## 5. Agent Instructions for Context Retrieval\n\n`;
    md += `- **MCP Query**: Use tool \`kb_explore\` with a symbol name to get full callers, blast radius, and verbatim code in 1 step.\n`;
    md += `- **Refactoring Check**: Use tool \`kb_impact\` before modifying functions to calculate breaking change risk.\n`;
    md += `- **Search**: Use tool \`kb_search\` for fast keyword & symbol lookups.\n`;
    md += `- **Local REST API**: Access \`http://127.0.0.1:7890/v1/explore\` directly from scripts.\n\n`;
    md += `---\n*Generated by OmniKB - 100% Local Real-Time Code Intelligence Engine.*\n`;

    await fs.promises.writeFile(targetFile, md, 'utf8');
    return targetFile;
  }

  /**
   * Generates interactive standalone HTML Graph visualizer (graph.html)
   */
  public async generateHtmlVisualizer(outputPath?: string): Promise<string> {
    const targetFile = outputPath || path.join(this.workspaceRoot, '.omnikb', 'graph.html');
    const nodes = Array.from(this.storage.nodes.values()).map((n) => ({
      id: n.id,
      name: n.name,
      kind: n.kind,
      file: n.filePath,
      line: n.startLine,
    }));

    const edges = Array.from(this.storage.edges.values()).map((e) => ({
      source: e.sourceId,
      target: e.targetId,
      kind: e.kind,
    }));

    const graphDataJson = JSON.stringify({ nodes, edges });

    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>OmniKB Interactive Code Graph Visualizer</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }
    body { background: #0f172a; color: #f8fafc; overflow: hidden; height: 100vh; display: flex; flex-direction: column; }
    header { background: #1e293b; padding: 12px 20px; display: flex; align-items: center; justify-content: space-between; border-bottom: 1px solid #334155; }
    h1 { font-size: 16px; font-weight: 600; color: #38bdf8; display: flex; align-items: center; gap: 8px; }
    .badge { background: #0284c7; color: white; padding: 2px 8px; border-radius: 9999px; font-size: 11px; }
    .stats { font-size: 13px; color: #94a3b8; display: flex; gap: 16px; }
    #container { flex: 1; position: relative; }
    svg { width: 100%; height: 100%; cursor: grab; }
    svg:active { cursor: grabbing; }
    .node-file { fill: #38bdf8; }
    .node-function { fill: #4ade80; }
    .node-class { fill: #f59e0b; }
    .node-interface { fill: #a855f7; }
    .node-route { fill: #f43f5e; }
    .node-doc { fill: #ec4899; }
    .edge { stroke: #475569; stroke-width: 1px; stroke-opacity: 0.6; }
    .edge-calls { stroke: #4ade80; stroke-dasharray: 4; }
    .edge-imports { stroke: #38bdf8; }
    .panel { position: absolute; top: 20px; right: 20px; width: 320px; background: rgba(30, 41, 59, 0.95); backdrop-filter: blur(8px); border: 1px solid #334155; border-radius: 8px; padding: 16px; box-shadow: 0 10px 25px rgba(0,0,0,0.5); font-size: 13px; }
    .panel h3 { font-size: 14px; margin-bottom: 8px; color: #38bdf8; }
    .panel p { margin-bottom: 6px; color: #cbd5e1; }
    .search-box { position: absolute; top: 20px; left: 20px; z-index: 10; display: flex; gap: 8px; }
    input[type="text"] { background: #1e293b; border: 1px solid #475569; color: white; padding: 8px 12px; border-radius: 6px; width: 260px; outline: none; }
    input[type="text"]:focus { border-color: #38bdf8; }
  </style>
</head>
<body>
  <header>
    <h1>OmniKB Code Graph <span class="badge">Live Local Engine</span></h1>
    <div class="stats">
      <span>Nodes: <strong id="nodeCount">${nodes.length}</strong></span>
      <span>Edges: <strong id="edgeCount">${edges.length}</strong></span>
      <span>Status: <strong style="color:#4ade80;">Auto-Synced</strong></span>
    </div>
  </header>
  <div id="container">
    <div class="search-box">
      <input type="text" id="searchInput" placeholder="Search function, class, file..." />
    </div>
    <div class="panel" id="detailPanel">
      <h3>Node Inspector</h3>
      <p id="nodeName">Click any node to inspect relationships, caller graph, and blast radius.</p>
      <p id="nodeMeta"></p>
    </div>
    <svg id="graphSvg"></svg>
  </div>

  <script src="https://d3js.org/d3.v7.min.js"></script>
  <script>
    const data = ${graphDataJson};
    const svg = d3.select("#graphSvg");
    const width = window.innerWidth;
    const height = window.innerHeight - 50;

    const g = svg.append("g");
    svg.call(d3.zoom().scaleExtent([0.1, 4]).on("zoom", (e) => g.attr("transform", e.transform)));

    const validNodeIds = new Set(data.nodes.map(n => n.id));
    const validEdges = data.edges.filter(e => validNodeIds.has(e.source) && validNodeIds.has(e.target));

    const simulation = d3.forceSimulation(data.nodes)
      .force("link", d3.forceLink(validEdges).id(d => d.id).distance(60))
      .force("charge", d3.forceManyBody().strength(-120))
      .force("center", d3.forceCenter(width / 2, height / 2))
      .force("collision", d3.forceCollide().radius(18));

    const link = g.append("g")
      .selectAll("line")
      .data(validEdges)
      .enter().append("line")
      .attr("class", d => "edge " + (d.kind === "calls" ? "edge-calls" : "edge-imports"));

    const node = g.append("g")
      .selectAll("circle")
      .data(data.nodes)
      .enter().append("circle")
      .attr("r", d => d.kind === "file" ? 8 : (d.kind === "class" ? 7 : 5))
      .attr("class", d => "node-" + (d.kind === "doc_section" ? "doc" : d.kind))
      .call(d3.drag()
        .on("start", dragstarted)
        .on("drag", dragged)
        .on("end", dragended))
      .on("click", (e, d) => {
        document.getElementById("nodeName").innerHTML = "<strong>" + d.name + "</strong> (" + d.kind + ")";
        document.getElementById("nodeMeta").innerHTML = "File: " + d.file + "<br>Line: " + d.line + "<br>ID: " + d.id;
      });

    const label = g.append("g")
      .selectAll("text")
      .data(data.nodes.slice(0, 150))
      .enter().append("text")
      .text(d => d.name)
      .attr("font-size", 10)
      .attr("fill", "#94a3b8")
      .attr("dx", 8)
      .attr("dy", 3);

    simulation.on("tick", () => {
      link
        .attr("x1", d => d.source.x)
        .attr("y1", d => d.source.y)
        .attr("x2", d => d.target.x)
        .attr("y2", d => d.target.y);

      node
        .attr("cx", d => d.x)
        .attr("cy", d => d.y);

      label
        .attr("x", d => d.x)
        .attr("y", d => d.y);
    });

    function dragstarted(event, d) {
      if (!event.active) simulation.alphaTarget(0.3).restart();
      d.fx = d.x;
      d.fy = d.y;
    }
    function dragged(event, d) {
      d.fx = event.x;
      d.fy = event.y;
    }
    function dragended(event, d) {
      if (!event.active) simulation.alphaTarget(0);
      d.fx = null;
      d.fy = null;
    }

    document.getElementById("searchInput").addEventListener("input", (e) => {
      const val = e.target.value.toLowerCase();
      node.attr("opacity", d => (val && !d.name.toLowerCase().includes(val)) ? 0.15 : 1);
      label.attr("opacity", d => (val && !d.name.toLowerCase().includes(val)) ? 0.15 : 1);
    });
  </script>
</body>
</html>`;

    await fs.promises.writeFile(targetFile, htmlContent, 'utf8');
    return targetFile;
  }
}
